config/routes.rb
Rails.application.routes.draw do
  
  resources :suggestions
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'
  
  get 'checkout' => 'cart#checkout'
  
  post 'order_complete' => 'cart#order_complete'

  resources :orders
  resources :line_items
  get 'all_items' => 'storefront#all_items'

  get 'category' => 'storefront#items_by_category'

  resources :products
  resources :destinations
  get '/random' => 'destinations#random'
  devise_for :users

  root 'destinations#index'

end

app/models/suggestion.rb
class Suggestion < ActiveRecord::Base
    validates :city, :presence => true
    validates :state, :presence => true
    validates :packing_list, :presence => true
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: [:show, :edit, :update, :destroy]

  # GET /suggestions
  # GET /suggestions.json
  def index
    @suggestions = Suggestion.all
  end

  # GET /suggestions/1
  # GET /suggestions/1.json
  def show
  end

  # GET /suggestions/new
  def new
    @suggestion = Suggestion.new
  end

  # GET /suggestions/1/edit
  def edit
  end

  # POST /suggestions
  # POST /suggestions.json
  def create
    @suggestion = Suggestion.new(suggestion_params)

    respond_to do |format|
      if @suggestion.save
        format.html { redirect_to new_suggestion_path, notice: 'Suggestion successfully submitted. The destination will be created upon approval by our admins.' }
        format.json { render :show, status: :created, location: @suggestion }
      else
        format.html { render :new }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /suggestions/1
  # PATCH/PUT /suggestions/1.json
  def update
    respond_to do |format|
      if @suggestion.update(suggestion_params)
        format.html { redirect_to @suggestion, notice: 'Suggestion was successfully updated.' }
        format.json { render :show, status: :ok, location: @suggestion }
      else
        format.html { render :edit }
        format.json { render json: @suggestion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /suggestions/1
  # DELETE /suggestions/1.json
  def destroy
    @suggestion.destroy
    respond_to do |format|
      format.html { redirect_to suggestions_url, notice: 'Suggestion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_suggestion
      @suggestion = Suggestion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def suggestion_params
      params.require(:suggestion).permit(:city, :state, :packing_list, :category)
    end
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/suggestions/_form.html.erb
<%= form_for(@suggestion) do |f| %>
  <% if @suggestion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@suggestion.errors.count, "error") %> prohibited this suggestion from being saved:</h2>

      <ul>
      <% @suggestion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :packing_list %><br>
    <%= f.text_area :packing_list %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/suggestions/edit.html.erb
<h1>Editing Suggestion</h1>

<%= render 'form' %>

<%= link_to 'Show', @suggestion %> |
<%= link_to 'Back', suggestions_path %>

app/views/suggestions/index.html.erb
<p style="color: green;"><%= notice %></p>

<h1></h1>

<div class= 'row'>
  <% if @suggestions.empty? %>
        <h3> There are no suggestions at this time. </h3>
  <% else %>      
  <% @suggestions.each do |suggestion| %>
    <div class='col-md-4'>
      <div class='panel panel-default'>
        <div class='panel-heading'>
          <h2><%= link_to suggestion.city, suggestion %></h2>
        </div>
        <div class='panel-body'>
          <h3><%= suggestion.state %></h3><br />
            <ul>
              <% suggestion.packing_list.split(",").each do |l|%>
              <li><%= l %></li>
              <%end%>
            </ul>
          <br>
        </div>
        <div class='panel-footer'>
          <%= link_to 'Destroy Suggestion',  { action: :destroy, id: suggestion.id }, method: :delete, data: { confirm: 'Are you sure?' } %>
          <br>
          <%= link_to 'Create Destination', new_destination_path(id: suggestion.id) %>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

<br>

app/views/suggestions/new.html.erb
<p id="notice"> <%= notice %> </p>
<br>
<h1>New Suggestion</h1>

<%= render 'form' %>

app/views/suggestions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>City:</strong>
  <%= @suggestion.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @suggestion.state %>
</p>

<p>
  <strong>Packing list:</strong>
  <%= @suggestion.packing_list %>
</p>

<p>
  <strong>Category:</strong>
  <%= @suggestion.category %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @suggestion.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @suggestion.updated_at %>
</p>

<p>
  <strong>Avatar file name:</strong>
  <%= @suggestion.avatar_file_name %>
</p>

<p>
  <strong>Avatar content type:</strong>
  <%= @suggestion.avatar_content_type %>
</p>

<p>
  <strong>Avatar file size:</strong>
  <%= @suggestion.avatar_file_size %>
</p>

<p>
  <strong>Avatar updated at:</strong>
  <%= @suggestion.avatar_updated_at %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @suggestion.slug %>
</p>

<%= link_to 'Edit', edit_suggestion_path(@suggestion) %> |
<%= link_to 'Back', suggestions_path %>