config/routes.rb
Rails.application.routes.draw do
  
  resources :suggestions
  post 'add_to_cart' => 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'
  
  get 'checkout' => 'cart#checkout'
  
  post 'order_complete' => 'cart#order_complete'

  resources :orders
  resources :line_items
  get 'all_items' => 'storefront#all_items'

  get 'category' => 'storefront#items_by_category'

  resources :products
  resources :destinations
  get '/random' => 'destinations#random'
  devise_for :users

  root 'destinations#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Travel Pack App</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js' %>
  <!--<script src="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css"></script>-->
  <!--<link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css" rel="stylesheet" integrity="sha256-sHwgyDk4CGNYom267UJX364ewnY4Bh55d53pxP5WDug= sha512-mkkeSf+MM3dyMWg3k9hcAttl7IVHe2BA1o/5xKLl4kBaP0bih7Mzz/DBy4y6cNZCHtE2tPgYBYH/KtEjOQYKxA==" crossorigin="anonymous">-->
  <%= csrf_meta_tags %>
</head>

<body>


<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Home</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><a href="/random">Random Destination</a></li>
        <li><a href="/suggestions/new">Suggest a Destination</a></li>
        <li>
             <%= form_tag destinations_path, method: :get do %>
                 <%= text_field_tag :q, nil, placeholder: "Search Destinations", id: "searchBar" %>
             <% end %>
          </li>
      </ul>
          
             
        <ul class="nav navbar-nav navbar-right">
          <% if user_signed_in? and current_user.admin? %>
              <li><a href="/suggestions">Suggestions</a></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <% @categories.each do |category| %>
                    <li><%= link_to category, category_path(category: category) %></li>
              <% end %>
            </ul>
          </li>
          <li><a href="/all_items">Store</a></li>
          <li><%= link_to view_order_path do %>
             <i class="glyphicon glyphicon-shopping-cart"></i>
          <% end %>
          </li>
        <% if user_signed_in? %>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
        </ul>
          
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<% if current_page?(root_path) %>
<div class="banner">
<div class="video">
<%= video_tag("ocean.mp4", autoplay: true, loop: true, muted: true, width:'100%') %>
</div>
<div class="banner_data">
<div class="banner_txt">
  <h2>Packer Hacker</h2> <br>
  <h5>Scroll down to view packing lists of popular destinations</h5> <br>
  <a onclick="window.scrollTo(0, 600)"span class="glyphicon glyphicon-circle-arrow-down" aria-hidden="true"></span></a>
</div>
</div>
</div>
<% end %>


<div class='container'>


<%= yield %>

</div>

</body>
</html>